security:
    encoders:
      App\Entity\User: bcrypt

    providers:
        database_users:
          entity:
            class: App\Entity\User
            property: username
        # in_memory: { memory: ~ }
    
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            provider: database_users
            form_login:
                check_path: login
                login_path: login
                csrf_token_generator: security.csrf.token_manager # protection against CSRF attacks
                default_target_path: app_mission_list
            logout:
                path: /logout
                target: /login
            anonymous: ~

    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/profil, roles: IS_AUTHENTICATED_FULLY }

        - { path: ^/missions/ajouter, roles: ROLE_GLA }
        - { path: ^/missions/voir, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/missions/modifier, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/missions/fermer, roles: ROLE_GLA }
        - { path: ^/missions/supprimer-pj, roles: ROLE_GLA }
        - { path: ^/missions/supprimer, roles: ROLE_GLA }
        - { path: ^/missions/assigner, roles: ROLE_VOLUNTEER }
        - { path: ^/missions/pdf, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/missions/recap, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/missions, roles: IS_AUTHENTICATED_FULLY }

        - { path: ^/logements/ajouter, roles: ROLE_GLA }
        - { path: ^/logements/modifier, roles: ROLE_GLA }
        - { path: ^/logements/supprimer, roles: ROLE_ADMIN }
        - { path: ^/logements/info, roles: ROLE_GLA }
        - { path: ^/logements, roles: IS_AUTHENTICATED_FULLY }

        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }

    role_hierarchy:
        ROLE_ADMIN: [ROLE_GLA, ROLE_VOLUNTEER]
