knp_snappy:
    pdf:
        enabled:    true
        binary:     '%env(WKHTMLTOPDF_PATH)%'
        options:    []
        
    image:
        enabled:    false
        # binary:     '%env(WKHTMLTOIMAGE_PATH)%'   (commented to avoid cache:clear error)
        options:    []
