# index:
#    path: /
#    controller: App\Controller\LuckyController::number

controllers:
    resource: '../src/Controller'
    type:     annotation

# redirecting the homepage
homepage:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: app_mission_list
        permanent: true

logout:
    path: /logout